version: "3"
services:
  redis:
    image: redis:latest
    container_name: redis-mmf
    networks:
      - d2api_default
    ports:
      - "6378:6379"
    restart: always

  mmf:
    build: ../
    image: relative-fi/mmf
    container_name: mmf
    restart: always
    env_file:
      - ../.env
    networks:
      - d2api_default
    ports:
      - "9876:9876"
    depends_on:
      - redis

networks:
  d2api_default:
    external: true
